"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


last_second = 0
last_first = 1

result = 0

current = 1

while current <= 40_00_000:
    if current%2 == 0:
        result += current
        
    last_second = last_first
    last_first = current
    current = last_first + last_second

print(result)